<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>HanyeMonitorControl</AssemblyName>
    <RootNamespace>HanyeMonitorControl</RootNamespace>
    <ApplicationIcon Condition="Exists('app-icon.ico')">app-icon.ico</ApplicationIcon>
    <Version>4.2.0</Version>
    <Product>hanye Printer Monitor</Product>
    <Company>hanye</Company>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
  </PropertyGroup>
</Project>
